language: go

go:
  - 1.11.x

services:
  - memcached
  - redis-server

go_import_path: github.com/Chyroc/wechat-go

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure -v
  - dep status
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./...)

notifications:
  email:
    on_success: never
    on_failure: never